name: Build and Push Docker Image

on:
  check_run:
    types: [rerequested, completed]

jobs:
  build:
      name: Build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Setup .NET Core  
          uses: actions/setup-dotnet@v3
          with:
            global-json: 'global.json'

        - name: Install dependencies
          run: dotnet restore
          working-directory: ./AutomatedTestingApp

        - name: Build
          run: | 
            dotnet build --configuration Release --no-restore

        - name: Publish
          run: dotnet publish --no-build --configuration Release --output ./publish