name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Setup dotnet  
          uses: actions/setup-dotnet@v1
          with:
            global-json: 'global.json'
        - name: Install dependencies
          run: dotnet restore
        - name: Build
          run: dotnet build --no-restore
        - name: Publish
          run: dotnet publish --no-build --configuration Release --output ./publish
            