name: Build and Publish

env:
  PROJECT_NAME: AutomatedTestingApp.csproj
  PROJECT_PATH: ./src/AutomatedTestingApp

on:
  check_run:
    types: [rerequested, completed]
  workflow_dispatch: 
  push:
  pull_request:

jobs:
  build:
      name: Build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Setup .NET Core  
          uses: actions/setup-dotnet@v3
          with:
            global-json: 'global.json'

        - name: Install dependencies
          run: dotnet restore
          working-directory: ./src

        - name: Build
          run: | 
            dotnet build ${{ env.PROJECT_NAME }} --configuration Release --no-restore
          working-directory: ${{ env.PROJECT_PATH }}

        - name: Publish
          run: |
            dotnet publish ${{ env.PROJECT_NAME }} --no-build --no-restore --configuration Release --output ./publish
          working-directory: ${{ env.PROJECT_PATH }}
          
        #TODO: Add tests here