name: Build and Publish

env:
  PROJECT_NAME: AutomatedTestingApp.csproj
  PROJECT_PATH: ./AutomatedTestingApp/AutomatedTestingApp

on:
  check_run:
    types: [rerequested, completed]
  workflow_dispatch: 

jobs:
  build:
      name: Build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Setup .NET Core  
          uses: actions/setup-dotnet@v3
          with:
            global-json: 'global.json'

        - name: Install dependencies
          run: dotnet restore
          working-directory: ./AutomatedTestingApp

        - name: Build
          run: | 
            dotnet build $PROJECT_NAME --configuration Release --no-restore
          working-directory: $PROJECT_PATH

        - name: Publish
          run: |
            dotnet publish $PROJECT_NAME --no-build --no-restore --configuration Release --output ./publish
          working-directory: $PROJECT_PATH
          
        #TODO: Add tests here